### ISSUE TITLE
r_lodCurveError 

### ISSUE THREAD

**Issue by WhiteMagicRaven** [Chomenor/ioef-cmod#1]
this cvar is cheat protected, actually this is not cheat cvar.
Its control level of detail, higher values removes LODS making them more beautiful.
Please allow to change this value to higher values but not less then 250, Thanks

Makes graphic better

**Comment by Chomenor** [comment]
This should be done in 6cd11c8d5e81ad6befc7fccc687dadf8b248b8b1. Thanks for the suggestion!

**Comment by WhiteMagicRaven** [comment]
Thanks =)
