### ISSUE TITLE
r_flares

### ISSUE THREAD

**Issue by WhiteMagicRaven** [Chomenor/ioef-cmod#2]
this cvar broken 
Should make light halos when set to 1, and no halos when 0

for now its no difference which value used

**Comment by Chomenor** [comment]
For me it does make a difference in the parts of the map that specifically use flares, like here:

![flares_on](https://user-images.githubusercontent.com/4357914/210933046-af462385-6670-431e-ac27-294f947945c5.jpg)
![flares_off](https://user-images.githubusercontent.com/4357914/210933048-ef7644f0-15de-4134-99fb-133ea8729a28.jpg)

Is this effect not working on your PC, or are you expecting some other different effect?

**Comment by WhiteMagicRaven** [comment]
yes then you right, that not work on my PC somehow. 
and it works with Lilium Voyager , hmm, i have no clue , the same engines all should work than?

**Comment by Chomenor** [comment]
Does it not work on both opengl1 and opengl2 renderers?

**Comment by WhiteMagicRaven** [comment]
Lilium both
cMod only opengl2

so its solved thanks for hint =)

cl_renderer opengl2

**Comment by Chomenor** [comment]
Try setting r_framebuffer to 0, and see if that fixes it on the opengl1 renderer.

**Comment by Chomenor** [comment]
I can confirm that there is a bug in the case of gl1 renderer + r_framebuffer 1 + r_multisample enabled. I'm guessing this might be what you encountered.

**Comment by WhiteMagicRaven** [comment]
Tried, exactly happens the same as you described.

**Comment by Chomenor** [comment]
This should now be fixed in 155ad8e1e931cd298cdd6a7a263451ea6021aca5. Thanks for the report!

**Comment by WhiteMagicRaven** [comment]
Thnks
