### ISSUE TITLE
ef_facade map and r_roundimagedown 0 

### ISSUE THREAD

**Issue by WhiteMagicRaven** [Chomenor/ioef-cmod#3]
i get error: Resample Texture max width , and map didn't load
cause r_roundimagedown 0 cvar 
this cvar helpful to remove resampling down textures making them sharp, a little bit sharper than just r_picmip 0.

can you extend please that max texture width please to bigger value.

**Comment by Chomenor** [comment]
This should now be fixed with ed5795460661a56edc9d9d886b901fbdbb369c44.

**Comment by WhiteMagicRaven** [comment]
Thanks)

**Comment by Chomenor** [comment]
Thanks for the report.
